### ISSUE TITLE
How to run this code?

### ISSUE THREAD

**Issue by moon0331** [EdmundYanJ/NS-ICF#2]
Hello.

I was very impressed since reading your paper and found this repository. 
But I have some trouble about running this NC-ICF model, because there seems to be no executable code here at once.
Could you please upload the code for run this model?
Thank you.

**Comment by 3256942614** [comment]
Hello, author,
       I read this paper of yours and I think it is very good, so I want to run it, but I can't find ml-1m and taobao, these two datasets, please the author can send these two datasets to me.
